source("src/packages.R")

# Load stan model fits
load("imptf-models/covid19model-6.0/results/env-europe-stanfit.Rdata")
europe <- unlist(rstan::extract(fit, "env_slp"))
load("imptf-models/covid19model-6.0/results/env-pop-usa-stanfit.Rdata")
usa.env.time.slp <- unlist(rstan::extract(fit, "env_time_slp"))
usa.env.const.slp <- unlist(rstan::extract(fit, "env_const_slp"))
usa.pop.slp <- unlist(rstan::extract(fit, "pop_slp"))
load("imptf-models/covid19model-6.0/results/env-brazil-stanfit.Rdata")
brazil <- unlist(rstan::extract(fit, "env_slp"))
load("imptf-models/covid19model-6.0/results/env-italy-stanfit.Rdata")
italy <- unlist(rstan::extract(fit, "env_slp"))

# Estimate impacts and probabilities
print("Europe:")
print(summary(europe))
print(sum(europe < 0) / length(europe))
print("\n\n")
print("USA:")
print(summary(usa.env.const.slp))
print(sum(usa.env.const.slp < 0) / length(usa.env.const.slp))
print(summary(usa.env.time.slp))
print(sum(usa.env.time.slp < 0) / length(usa.env.time.slp))
print(summary(usa.pop.slp))
print(sum(usa.pop.slp < 0) / length(usa.pop.slp))
print("\n\n")
print("Brazil:")
print(summary(brazil))
print(sum(brazil < 0) / length(brazil))
print("\n\n")
print("Italy:")
print(summary(italy))
print(sum(italy < 0) / length(italy))
print("\n\n")
